<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="cxyarm">
    <!--constand the dimension-->
    <xacro:property name="PI" value="3.1415926535" />
    <xacro:property name="mass" value="1" /> <!-- arbitrary value for mass -->
    <xacro:property name="width" value="1" /> <!-- Square dimensions (widthxwidth) of beams -->
    <xacro:property name="height0" value="8"/> <!-- link0-->
    <xacro:property name="height1" value="0.3" /> <!-- Link 1 -->
    <xacro:property name="height2" value="11.5" /> <!-- Link 2 -->
    <xacro:property name="height3" value="12.5" /> <!-- Link 3 -->
    <xacro:property name="height4" value="15" /> <!-- Link 4 -->
    <!--<xacro:property name="camera_link" value="05" /> Size of square 'camera' box -->
    <xacro:property name="axel_offset" value="0.05" /> <!-- Space btw top of beam and the each joint -->

    <xacro:include filename="$(find cxy_arm_description)/urdf/materials.xacro" />
    <xacro:include filename="$(find cxy_arm_description)/urdf/cxyarm.gazebo" />

    <link name="world" />

    <joint name="fixed" type="fixed">
        <parent link="world" />
        <child link="link0" />
    </joint>

    <link name="link0">
        <collision>
            <origin xyz="0 0 ${height0/2}" rpy="0 0 0" />
            <geometry>
                <!--<box size="${width} ${width} ${height0}" /> -->
                <cylinder radius="2" length="${height0}"/>
            </geometry>
        </collision>

        <visual>
            <origin xyz="0 0 ${height0/2}" rpy="0 0 0" />
            <geometry>
                <!--<box size="${width} ${width} ${height1}" />-->
                <cylinder radius="2" length="${height0}"/>
            </geometry>
            <material name="black" />
        </visual>

        <inertial>
            <origin xyz="0 0 ${height0/2}" rpy="0 0 0" />
            <mass value="${mass}" />
            <inertia ixx="${mass / 12.0 * (width*width + height0*height0)}" ixy="0" ixz="0" iyy="${mass / 12.0 * (height0*height0 + width*width)}" iyz="0" izz="${mass / 12.0 * (width*width + width*width)}" />
        </inertial>
    </link>

    <joint name="joint0" type="continuous">
        <origin xyz="0 0 ${height0-axel_offset}" rpy="${PI/2} 0 ${PI/2}" />
        <parent link="link0" />
        <child link="link1" />
        <axis xyz="0 1 0" />
        <dynamics damping="0.7" />
    </joint>

    <link name="link1">
        <collision>
            <origin xyz="0 0 ${height1/2}" rpy="0 0 0" />
            <geometry>
                <!--<box size="${width} ${width} ${height1}" />-->
                <sphere radius="1"/>
            </geometry>
        </collision>

        <visual>
            <origin xyz="0 0 ${height1/2}" rpy="0 0 0" />
            <geometry>
                <!--<box size="${width} ${width} ${height1}" />-->
                <sphere radius="1"/>
            </geometry>
            <material name="red" />
        </visual>

        <inertial>
            <origin xyz="0 0 ${height1/2}" rpy="0 0 0" />
            <mass value="${mass}" />
            <inertia ixx="${mass / 12.0 * (width*width + height1*height1)}" ixy="0" ixz="0" iyy="${mass / 12.0 * (height1*height1 + width*width)}" iyz="0" izz="${mass / 12.0 * (width*width + width*width)}" />
        </inertial>
    </link>

    <joint name="joint1" type="continuous">
        <origin xyz="0 0 ${height1-axel_offset}" rpy="${-PI/2} ${-PI/2} 0" />
        <parent link="link1" />
        <child link="link2" />
        <axis xyz="0 1 0" />
        <dynamics damping="0.7" />
    </joint>

    <link name="link2">
        <inertial>
            <origin xyz="0 0 ${height2/2-axel_offset}" rpy="0 0 0" />
            <mass value="${mass}" />
            <inertia ixx="${mass / 12.0 * (width*width + height2*height2)}" ixy="0" ixz="0" iyy="${mass / 12.0 * (height2*height2 + width*width)}" iyz="0" izz="${mass / 12.0 * (width*width + width*width)}" />
        </inertial>
        <visual name="">
            <origin xyz="0 0 ${height2/2-axel_offset}" rpy="0 0 0" />
            <geometry>
                <box size="${width} ${width} ${height2}" />
            </geometry>
            <material name="green" />
        </visual>
        <collision>
            <origin xyz="0 0 ${height2/2-axel_offset}" rpy="0 0 0" />
            <geometry>
                <box size="${width} ${width} ${height2}" />
            </geometry>
        </collision>
    </link>
    
    <joint name="joint2" type="continuous">
        <origin xyz="0 0 ${height2-axel_offset}" rpy="0 0 0" />
        <parent link="link2" />
        <child link="link3" />
        <axis xyz="0 1 0" />
        <dynamics damping="0.7" />
    </joint>

    <link name="link3">
        <inertial>
            <origin xyz="0 0 ${height3/2-axel_offset}" rpy="0 0 0" />
            <mass value="${mass}" />
            <inertia ixx="${mass / 12.0 * (width*width + height3*height3)}" ixy="0" ixz="0" iyy="${mass / 12.0 * (height3*height3 + width*width)}" iyz="0" izz="${mass / 12.0 * (width*width + width*width)}" />
        </inertial>
        <visual name="">
            <origin xyz="0 0 ${height3/2-axel_offset}" rpy="0 0 0" />
            <geometry>
                <box size="${width} ${width} ${height3}" />
            </geometry>
            <material name="blue" />
        </visual>
        <collision>
            <origin xyz="0 0 ${height3/2-axel_offset}" rpy="0 0 0" />
            <geometry>
                <box size="${width} ${width} ${height3}" />
            </geometry>
        </collision>
    </link>

    <joint name="joint3" type="continuous">
        <origin xyz="0 0 ${height3-axel_offset}" rpy="0 0 0" />
        <parent link="link3" />
        <child link="link4" />
        <axis xyz="0 1 0" />
        <dynamics damping="0.7" />
    </joint>

    <link name="link4">
        <inertial>
            <origin xyz="0 0 ${height4/2-axel_offset}" rpy="0 0 0" />
            <mass value="${mass}" />
            <inertia ixx="${mass / 12.0 * (width*width + height4*height4)}" ixy="0" ixz="0" iyy="${mass / 12.0 * (height4*height4 + width*width)}" iyz="0" izz="${mass / 12.0 * (width*width + width*width)}" />
        </inertial>
        <visual name="">
            <origin xyz="0 0 ${height4/2-axel_offset}" rpy="0 0 0" />
            <geometry>
                <box size="${width} ${width} ${height4}" />
            </geometry>
            <material name="orange" />
        </visual>
        <collision>
            <origin xyz="0 0 ${height4/2-axel_offset}" rpy="0 0 0" />
            <geometry>
                <box size="${width} ${width} ${height4}" />
            </geometry>
        </collision>
    </link>

    <transmission name="tran0">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="joint0">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="motor0">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

    <transmission name="tran1">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="joint1">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="motor1">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

    <transmission name="tran2">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="joint2">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="motor2">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

    <transmission name="tran3">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="joint3">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="motor3">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

</robot>